// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Create a fallback dummy client for when env vars aren't set (like in CI)
const createDummyClient = () => {
  console.warn('Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY. Supabase features will not work. See .env.example.');
  // Create a minimal dummy client to prevent immediate errors
  return {
    auth: {
      signUp: () => ({ data: null, error: new Error('Supabase not configured') }),
      signIn: () => ({ data: null, error: new Error('Supabase not configured') }),
      signOut: () => ({ error: null }),
      getUser: () => ({ data: { user: null }, error: null }),
      getSession: () => ({ data: { session: null }, error: null }),
      onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
    },
    from: () => ({
      select: () => ({ data: [], error: null }),
      insert: () => ({ data: null, error: null }),
      update: () => ({ data: null, error: null }),
      delete: () => ({ data: null, error: null }),
    }),
    storage: {
      from: () => ({
        upload: () => ({ data: null, error: null }),
        getPublicUrl: () => ({ data: { publicUrl: '' } }),
      }),
    },
  } as unknown as ReturnType<typeof createClient<Database>>;
};

// Only create the real client if we have both env vars
let supabaseInstance: ReturnType<typeof createClient<Database>>;
if (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY) {
  supabaseInstance = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
} else {
  supabaseInstance = createDummyClient();
}

export const supabase = supabaseInstance;
